
IF DB_ID('Airlines_Stage') IS NOT NULL
    DROP DATABASE Airlines_Stage;
GO

CREATE DATABASE Airlines_Stage;
GO

USE Airlines_Stage;
GO


CREATE TABLE Airlines_stg (
    IATA_CODE VARCHAR(10),
    AIRLINE VARCHAR(100),
    _ExtractTime DATETIME2(3) DEFAULT SYSDATETIME()
);
GO

CREATE TABLE Airports_stg (
    IATA_CODE VARCHAR(10),
    AIRPORT VARCHAR(150),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    _ExtractTime DATETIME2(3) DEFAULT SYSDATETIME()
);
GO

CREATE TABLE Flights_stg (
    FLIGHT_DATE DATE,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER VARCHAR(20),
    TAIL_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT VARCHAR(10),
    DESTINATION_AIRPORT VARCHAR(10),
    SCHEDULED_DEPARTURE INT,
    DEPARTURE_TIME INT,
    DEPARTURE_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF INT,
    SCHEDULED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    WHEELS_ON INT,
    TAXI_IN FLOAT,
    SCHEDULED_ARRIVAL INT,
    ARRIVAL_TIME INT,
    ARRIVAL_DELAY FLOAT,
    DIVERTED BIT,
    CANCELLED BIT,
    CANCELLATION_REASON CHAR(1),
    AIR_SYSTEM_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    AIRLINE_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    _ExtractTime DATETIME2(3) DEFAULT SYSDATETIME()
);
GO
/*
DELETE FROM Airlines_stg
DELETE FROM Airports_stg
DELETE FROM Flights_stg
*/
SELECT * FROM Airlines_stg
SELECT * FROM Airports_stg
SELECT * FROM Flights_stg